dist: bionic

language: node_js

cache: npm

node_js:
  - "6"
  - "7"
  - "8.11"
  - "10.16"
  - "12"
  - "14"

script:
  - yarn test
  - echo $COVERALLS_TOKEN | tee .coveralls.yml
  - yarn coveralls:push
